# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

def base(name)
  if name.kind_of? Array
    name.map { |x| base(x) }
  else
    "../../#{name}"
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  config.vm.box = "kjunine/trusty64"

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.8.10"
    master.vm.network "forwarded_port", guest: 2375, host: 2376

    master.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = base(["cookbooks", "site-cookbooks"])
      chef.roles_path = base("roles")
      chef.environments_path = base("environments")
      chef.data_bags_path = base("data_bags")
      chef.add_role "mongodb"
      chef.add_role "redis-master"
    end
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = "slave"
    slave.vm.network "private_network", ip: "192.168.8.11"
    slave.vm.network "forwarded_port", guest: 2375, host: 2377

    slave.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = base(["cookbooks", "site-cookbooks"])
      chef.roles_path = base("roles")
      chef.environments_path = base("environments")
      chef.data_bags_path = base("data_bags")
      chef.add_role "mongodb"
      chef.add_role "redis-slave"
    end
  end
end
